"""empty message

Revision ID: 30b560ea1ee3
Revises: 4930942ca695
Create Date: 2015-04-16 11:47:16.594840

"""

# revision identifiers, used by Alembic.
revision = '30b560ea1ee3'
down_revision = '4930942ca695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
