"""empty message

Revision ID: 33a038d1ddb2
Revises: e75a3a8eb19
Create Date: 2015-04-14 15:55:15.423485

"""

# revision identifiers, used by Alembic.
revision = '33a038d1ddb2'
down_revision = 'e75a3a8eb19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
