"""empty message

Revision ID: 357ba81b81ef
Revises: 35def4283bb
Create Date: 2015-04-14 12:13:55.402082

"""

# revision identifiers, used by Alembic.
revision = '357ba81b81ef'
down_revision = '35def4283bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendingtxs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('received_inputs', sa.Boolean(), nullable=True),
    sa.Column('outputs_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendingtxs')
    ### end Alembic commands ###
