"""empty message

Revision ID: 35def4283bb
Revises: None
Create Date: 2015-04-10 15:24:04.105009

"""

# revision identifiers, used by Alembic.
revision = '35def4283bb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('pending_amt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    ### end Alembic commands ###
