"""empty message

Revision ID: 3c2b6c7cc7c5
Revises: 30b560ea1ee3
Create Date: 2015-04-17 17:42:52.563132

"""

# revision identifiers, used by Alembic.
revision = '3c2b6c7cc7c5'
down_revision = '30b560ea1ee3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('txs', sa.Column('origin', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('txs', 'origin')
    op.drop_column('nodes', 'origin')
    ### end Alembic commands ###
