"""empty message

Revision ID: 4930942ca695
Revises: f98d44dc9fc
Create Date: 2015-04-16 11:12:13.020032

"""

# revision identifiers, used by Alembic.
revision = '4930942ca695'
down_revision = 'f98d44dc9fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
