"""empty message

Revision ID: e75a3a8eb19
Revises: 357ba81b81ef
Create Date: 2015-04-14 13:09:07.166208

"""

# revision identifiers, used by Alembic.
revision = 'e75a3a8eb19'
down_revision = '357ba81b81ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
