"""empty message

Revision ID: f98d44dc9fc
Revises: 33a038d1ddb2
Create Date: 2015-04-16 11:05:29.678164

"""

# revision identifiers, used by Alembic.
revision = 'f98d44dc9fc'
down_revision = '33a038d1ddb2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('received_inputs', sa.Boolean(), nullable=True),
    sa.Column('outputs_sent', sa.Boolean(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('pending_amt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pendingtxs')
    op.drop_table('wallets')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pending_amt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'wallets_pkey')
    )
    op.create_table('pendingtxs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('received_inputs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('outputs_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'pendingtxs_pkey')
    )
    op.drop_table('nodes')
    op.drop_table('txs')
    ### end Alembic commands ###
