"""empty message

Revision ID: 2f37642c479
Revises: 45eae38bccea
Create Date: 2015-05-04 12:31:46.110550

"""

# revision identifiers, used by Alembic.
revision = '2f37642c479'
down_revision = '45eae38bccea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('txs', 'timestamp')
    ### end Alembic commands ###
