"""empty message

Revision ID: 45eae38bccea
Revises: 55932d2e0537
Create Date: 2015-04-20 18:58:27.868209

"""

# revision identifiers, used by Alembic.
revision = '45eae38bccea'
down_revision = '55932d2e0537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
