"""empty message

Revision ID: 55932d2e0537
Revises: None
Create Date: 2015-04-20 14:25:07.989571

"""

# revision identifiers, used by Alembic.
revision = '55932d2e0537'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('pending_amt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('received_inputs', sa.Boolean(), nullable=True),
    sa.Column('outputs_sent', sa.Boolean(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('txs')
    op.drop_table('nodes')
    ### end Alembic commands ###
